//
//  DZImage.swift
//  Deadzone
//
//  Created by heyji on 2024/04/03.
//

import UIKit

enum DZImage {
    static var deadzone: UIImage = UIImage(resource: .deadzone)
    static var nextButton: UIImage = UIImage(resource: .next)
    static var addasset: UIImage = UIImage(resource: .addasset)
    static var archive: UIImage = UIImage(resource: .archive)
    static var on: UIImage = UIImage(resource: .on)
    static var off: UIImage = UIImage(resource: .off)
    static var pageControl1: UIImage = UIImage(resource: .pageControl1)
    static var pageControl2: UIImage = UIImage(resource: .pageControl2)
    static var pageControl3: UIImage = UIImage(resource: .pageControl3)
    static var passDefault: UIImage = UIImage(resource: .passdefault)
    static var passActive: UIImage = UIImage(resource: .passactive)
    static var settings: UIImage = UIImage(resource: .settings)
    static var alarm: UIImage = UIImage(resource: .alarm)
    static var back: UIImage = UIImage(resource: .back)
    static var sofa: UIImage = UIImage(resource: .sofa)
    static var table: UIImage = UIImage(resource: .table)
    static var fashion01: UIImage = UIImage(resource: .fashion01)
    static var fashion02: UIImage = UIImage(resource: .fashion02)
    static var cdplayer: UIImage = UIImage(resource: .cdplayer)
    static var meditation: UIImage = UIImage(resource: .meditation)
    static var reading: UIImage = UIImage(resource: .reading)
    static var wasted: UIImage = UIImage(resource: .wasted)
    static var iceCoffee: UIImage = UIImage(resource: .iceCoffee)
    static var music01: UIImage = UIImage(resource: .music01)
    static var cafe02: UIImage = UIImage(resource: .cafe02)
    static var meditation03: UIImage = UIImage(resource: .meditation03)
    static var reading04: UIImage = UIImage(resource: .reading04)
    static var drinking05: UIImage = UIImage(resource: .drinking05)
    static var fashion06: UIImage = UIImage(resource: .fashion06)
    static var defaultBM: UIImage = UIImage(resource: .defaultBM)
    static var pointBM: UIImage = UIImage(resource: .pointBM)
    static var border: UIImage = UIImage(resource: .border)
    static var caption: UIImage = UIImage(resource: .caption)
    static var npcWording: UIImage = UIImage(resource: .npcWording)
    static var check: UIImage = UIImage(resource: .check)
    static var defaultCheck: UIImage = UIImage(resource: .defaultCheck)
    static var activeCheck: UIImage = UIImage(resource: .activeCheck)
    static var xmark: UIImage = UIImage(resource: .xmark)
    static var largeDoor: UIImage = UIImage(resource: .largeDoor)
    static var mediumDoor: UIImage = UIImage(resource: .mediumDoor)
    static var smallDoor: UIImage = UIImage(resource: .smallDoor)
    static var uparrow: UIImage = UIImage(resource: .uparrow)
    static var profile: UIImage = UIImage(resource: .profile)
    static var termsCheckOn: UIImage = UIImage(resource: .termsCheckOn)
    static var termsCheckOff: UIImage = UIImage(resource: .termsCheckOff)
    static var vector: UIImage = UIImage(resource: .vector)
    static var selectedVector: UIImage = UIImage(resource: .selectedVector)
    static var askVector: UIImage = UIImage(resource: .askVector)
    static var answerVector: UIImage = UIImage(resource: .answerVector)
    static var journal: UIImage = UIImage(resource: .journal)
    static var announcement: UIImage = UIImage(resource: .announcement)
    static var knock: UIImage = UIImage(resource: .knock)
}
